repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '-f=lf' ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - license_header.txt        # defaults to: LICENSE.txt
          - --use-current-year
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: ['--fix', '--preview']
      - id: ruff-format
        args: ['--preview']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
      - id: mypy
        args: ['--warn-unused-ignores']
        additional_dependencies:
          - pydantic<2.6  # 2.6 does not support python 3.7
          - packaging
          - toml
          - pyparsing
          - types-PyYAML
          - types-toml
          - pytest<8  # 8.0.0 does not support python 3.7
