repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '-f=lf' ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - license_header.txt        # defaults to: LICENSE.txt
          - --use-current-year
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.6.2'
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
      - id: mypy
        args: ['--warn-unused-ignores']
        additional_dependencies:
          - pydantic
          - packaging
          - toml
          - pyparsing
          - types-PyYAML
          - types-toml
          - pytest
          - argcomplete>=3
  - repo: https://github.com/hfudev/rstfmt
    rev: v0.1.4
    hooks:
      - id: rstfmt
        args: ['-w', '-1']
        files: "docs\/.+rst$"
        additional_dependencies:
          - sphinx-argparse
          - sphinxcontrib-mermaid
